### ISSUE TITLE
cannot import name 'Lightning' from partially initialized module 'lightning'

### ISSUE THREAD

**Issue by 78bash** [wintercooled/NodeMonitor#4]
~/NodeMonitor-Python-Django$ python3 manage.py check --deploy
Traceback (most recent call last):
  File "/home/trenaz/NodeMonitor-Python-Django/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/management/commands/check.py", line 63, in handle
    self.check(
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/trenaz/NodeMonitor-Python-Django/nodemonitor/urls.py", line 5, in <module>
    url(r'^dashboard/', include('dashboard.urls')),
  File "/home/trenaz/.local/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/trenaz/NodeMonitor-Python-Django/dashboard/urls.py", line 3, in <module>
    from dashboard import views
  File "/home/trenaz/NodeMonitor-Python-Django/dashboard/views.py", line 84, in <module>
    from lightning import LightningRpc
  File "/home/trenaz/.local/lib/python3.9/site-packages/lightning/__init__.py", line 4, in <module>
    from .types.plots import *
  File "/home/trenaz/.local/lib/python3.9/site-packages/lightning/types/plots.py", line 2, in <module>
    from lightning.types.decorators import viztype
  File "/home/trenaz/.local/lib/python3.9/site-packages/lightning/types/decorators.py", line 87, in <module>
    from lightning import Lightning
ImportError: cannot import name 'Lightning' from partially initialized module 'lightning' (most likely due to a circular import) (/home/trenaz/.local/lib/python3.9/site-packages/lightning/__init__.py)

**Comment by 78bash** [comment]
I was trying to follow the instructions:
[here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment)

**Comment by wintercooled** [comment]
Hiya. Did it work when it was running locally without the attempt to deploy?

I haven't looked at this in a while but I can power it up after the weekend and take a look.

Perhaps one of the dependancies has been updated or something.

Normally this error is because you import something that references something that references the file doing the import - or you have a file named the same as one of the dependancies you are importing - which I don't think happens anywhere.

**Comment by 78bash** [comment]
Hi, It works perfectly without deployment, but I'm trying to follow the instructions to access the monitor from the web. -------- Original message --------From: Matthew Haywood ***@***.***>Date: Sat, Jul 31, 2021, 10:06 AMTo: wintercooled/NodeMonitor-Python-Django ***@***.***>Cc: bashir barrage ***@***.***>, Author ***@***.***>Subject: Re: [wintercooled/NodeMonitor-Python-Django] cannot import name 'Lightning' from partially initialized module 'lightning' (#4)
Hiya. Did it work when it was running locally without the attempt to deploy?
I haven't looked at this in a while but I can power it up after the weekend and take a look.
Perhaps one of the dependancies has been updated or something.
Normally this error is because you import something that references something that references the file doing the import - or you have a file named the same as one of the dependancies you are importing - which I don't think happens anywhere.
